import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          DetailPage(),
        ]),
      ),
    );
  }
}

class DetailPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 414,
          height: 896,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 24,
                top: 783,
                child: Container(
                  width: 373,
                  height: 80.29,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 147.34,
                        top: 0,
                        child: Container(
                          width: 225.66,
                          height: 80,
                          padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 16),
                          decoration: ShapeDecoration(
                            color: Color(0xFF00D18A),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(16),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3D0038FF),
                                blurRadius: 19,
                                offset: Offset(0, 6),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Text(
                                'Book Now',
                                style: TextStyle(
                                  color: Colors.white,
                                  fontSize: 16,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w900,
                                  height: 0,
                                ),
                              ),
                              const SizedBox(width: 10),
                              Container(
                                width: 24,
                                height: 24,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 4.75,
                                      top: 17.75,
                                      child: Transform(
                                        transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                        child: Container(
                                          width: 12.05,
                                          height: 15,
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 13,
                        child: Container(
                          width: 147,
                          height: 67.29,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 35,
                                top: 0,
                                child: SizedBox(
                                  width: 44,
                                  height: 21,
                                  child: Text(
                                    'PRICE',
                                    style: TextStyle(
                                      color: Color(0xFF232323),
                                      fontSize: 14,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w900,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 26.29,
                                child: SizedBox(
                                  width: 147,
                                  height: 41,
                                  child: Text(
                                    'Rp.990K',
                                    style: TextStyle(
                                      color: Color(0xFF2CD6A3),
                                      fontSize: 24,
                                      fontFamily: 'Montserrat',
                                      fontWeight: FontWeight.w700,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 643,
                child: Container(
                  width: 339,
                  height: 123,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 82.98,
                          height: 26.71,
                          child: Text(
                            'Facilities',
                            style: TextStyle(
                              color: Color(0xFF232323),
                              fontSize: 18,
                              fontFamily: 'Montserrat',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 33.14,
                        child: Container(
                          width: 339,
                          height: 89.86,
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                                decoration: ShapeDecoration(
                                  gradient: LinearGradient(
                                    begin: Alignment(-1.00, 0.01),
                                    end: Alignment(1, -0.01),
                                    colors: [Color(0xFF176EF2), Color(0xFF186EEE)],
                                  ),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(16),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 32,
                                      height: 32,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Stack(children: [
                                      ,
                                      ]),
                                    ),
                                    const SizedBox(height: 6),
                                    Text(
                                      '1 Heater',
                                      style: TextStyle(
                                        color: Color(0xFFB7B7B7),
                                        fontSize: 10,
                                        fontFamily: 'Poppins',
                                        fontWeight: FontWeight.w900,
                                        height: 0,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(width: 14),
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                                decoration: ShapeDecoration(
                                  gradient: LinearGradient(
                                    begin: Alignment(-1.00, 0.01),
                                    end: Alignment(1, -0.01),
                                    colors: [Color(0xFF176EF2), Color(0xFF186EEE)],
                                  ),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(16),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 32,
                                      height: 32,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Stack(children: [
                                      ,
                                      ]),
                                    ),
                                    const SizedBox(height: 6),
                                    Text(
                                      'Dinner',
                                      style: TextStyle(
                                        color: Color(0xFFC8C8C8),
                                        fontSize: 10,
                                        fontFamily: 'Poppins',
                                        fontWeight: FontWeight.w900,
                                        height: 0,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(width: 14),
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                                decoration: ShapeDecoration(
                                  gradient: LinearGradient(
                                    begin: Alignment(-1.00, 0.01),
                                    end: Alignment(1, -0.01),
                                    colors: [Color(0xFF176EF2), Color(0xFF186EEE)],
                                  ),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(16),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 44,
                                      height: 34,
                                      child: Stack(
                                        children: [
                                          Positioned(
                                            left: 1.50,
                                            top: 5.06,
                                            child: Container(
                                              width: 39.93,
                                              height: 29.95,
                                              child: Stack(children: [
                                              ,
                                              ]),
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                    const SizedBox(height: 6),
                                    Text(
                                      '1 Bed',
                                      style: TextStyle(
                                        color: Color(0xFFC8C8C8),
                                        fontSize: 10,
                                        fontFamily: 'Poppins',
                                        fontWeight: FontWeight.w900,
                                        height: 0,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                              const SizedBox(width: 14),
                              Container(
                                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 12),
                                decoration: ShapeDecoration(
                                  gradient: LinearGradient(
                                    begin: Alignment(-1.00, 0.01),
                                    end: Alignment(1, -0.01),
                                    colors: [Color(0xFF176EF2), Color(0xFF186EEE)],
                                  ),
                                  shape: RoundedRectangleBorder(
                                    borderRadius: BorderRadius.circular(16),
                                  ),
                                ),
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  children: [
                                    Container(
                                      width: 32,
                                      height: 32,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Stack(children: [
                                      ,
                                      ]),
                                    ),
                                    const SizedBox(height: 6),
                                    Text(
                                      'Pool',
                                      style: TextStyle(
                                        color: Color(0xFFC8C8C8),
                                        fontSize: 10,
                                        fontFamily: 'Poppins',
                                        fontWeight: FontWeight.w900,
                                        height: 0,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 444,
                child: Container(
                  width: 339,
                  height: 175,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 76.77,
                        child: SizedBox(
                          width: 339,
                          height: 77.77,
                          child: Text(
                            'Mount Bromo is one of the active volcanoes in Indonesia. The mountain is located in Probolinggo, East Java, with an altitude of 2,392 meters above sea level. Mount Bromo is one of the main tourist attractions in East Java.
                            \n',
                            style: TextStyle(
                              color: Color(0xFF3A544F),
                              fontSize: 12,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w300,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 147.55,
                        child: Container(
                          width: 99.17,
                          height: 27.45,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 2.29,
                                child: SizedBox(
                                  width: 70.84,
                                  height: 19.44,
                                  child: Text(
                                    'Read more',
                                    style: TextStyle(
                                      color: Color(0xFF176EF2),
                                      fontSize: 14,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w500,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 74.88,
                                top: 27.45,
                                child: Transform(
                                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                                  child: Container(
                                    width: 27.45,
                                    height: 24.29,
                                    clipBehavior: Clip.antiAlias,
                                    decoration: ShapeDecoration(
                                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                    ),
                                    child: Stack(children: [
                                    ,
                                    ]),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 3.04,
                        top: 10.44,
                        child: Container(
                          width: 335.96,
                          height: 48.59,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 28.59,
                                child: Container(
                                  width: 128,
                                  height: 20,
                                  child: Row(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment: CrossAxisAlignment.center,
                                    children: [
                                      Container(
                                        width: 128,
                                        height: 20,
                                        child: Stack(
                                          children: [
                                            Positioned(
                                              left: 0,
                                              top: 0,
                                              child: Container(
                                                width: 16,
                                                height: 16,
                                                child: Stack(children: [
                                                ,
                                                ]),
                                              ),
                                            ),
                                            Positioned(
                                              left: 20,
                                              top: 2,
                                              child: Text(
                                                '4.5 (355 Reviews)',
                                                style: TextStyle(
                                                  color: Color(0xFF5F5F5F),
                                                  fontSize: 12,
                                                  fontFamily: 'Poppins',
                                                  fontWeight: FontWeight.w500,
                                                  height: 0,
                                                ),
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 266.14,
                                top: 0,
                                child: SizedBox(
                                  width: 69.82,
                                  height: 19.44,
                                  child: Text(
                                    'Show map',
                                    style: TextStyle(
                                      color: Color(0xFF176EF2),
                                      fontSize: 14,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w500,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 195.30,
                          height: 33.17,
                          child: Text(
                            'Mt. Bromo',
                            style: TextStyle(
                              color: Color(0xFF232323),
                              fontSize: 24,
                              fontFamily: 'Montserrat',
                              fontWeight: FontWeight.w600,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 55,
                child: Container(
                  width: 369,
                  height: 384.74,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 369,
                          height: 361,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/369x361"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(20),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 289,
                        top: 338,
                        child: Container(
                          width: 44.53,
                          height: 46.74,
                          decoration: ShapeDecoration(
                            color: Color(0xFFF2F7FD),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(80),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x190038FF),
                                blurRadius: 19,
                                offset: Offset(0, 6),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Stack(
                            children: [
                              Positioned(
                                left: 9.54,
                                top: 11.68,
                                child: Container(
                                  width: 25.11,
                                  height: 25.04,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 25.11,
                                        top: 0,
                                        child: Transform(
                                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(3.14),
                                          child: Container(
                                            width: 25.11,
                                            height: 25.04,
                                            decoration: BoxDecoration(
                                              image: DecorationImage(
                                                image: NetworkImage("https://via.placeholder.com/25x25"),
                                                fit: BoxFit.fill,
                                              ),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 25.11,
                                          height: 25.04,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/25x25"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 22.14,
                        top: 30.75,
                        child: Container(
                          width: 40.48,
                          height: 42.49,
                          clipBehavior: Clip.antiAlias,
                          decoration: ShapeDecoration(
                            color: Color(0xFFF3F8FE),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                          child: Stack(children: [
                          ,
                          ]),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 16,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        '9:41',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF4F4F4F),
                          fontSize: 15,
                          fontFamily: 'SF Pro Text',
                          fontWeight: FontWeight.w600,
                          height: 0.09,
                          letterSpacing: -0.24,
                        ),
                      ),
                      const SizedBox(width: 277),
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 17,
                              height: 10.67,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/17x11"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 8),
                            Container(
                              width: 15.33,
                              height: 11,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/15x11"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 8),
                            Container(
                              width: 24.66,
                              height: 11,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Opacity(
                                      opacity: 0.35,
                                      child: Container(
                                        width: 22,
                                        height: 11,
                                        decoration: ShapeDecoration(
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(width: 1, color: Color(0xFF4F4F4F)),
                                            borderRadius: BorderRadius.circular(2.67),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 2,
                                    top: 2,
                                    child: Container(
                                      width: 18,
                                      height: 7,
                                      decoration: ShapeDecoration(
                                        color: Color(0xFF4F4F4F),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(1.33),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}