import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          MainPage(),
        ]),
      ),
    );
  }
}

class MainPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 414,
          height: 896,
          decoration: BoxDecoration(color: Colors.white),
          child: Stack(
            children: [
              Positioned(
                left: 9,
                top: 157,
                child: Container(
                  width: 697,
                  height: 230,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: -1,
                        top: 0,
                        child: Container(
                          width: 148,
                          height: 209,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 1,
                                top: 0,
                                child: Container(
                                  width: 147,
                                  height: 209,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/147x209"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1,
                                top: 178.75,
                                child: Container(
                                  width: 147,
                                  height: 30.25,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, -1.00),
                                      end: Alignment(0, 1),
                                      colors: [Color(0x00D9D9D9), Color(0xFF1E1E1E)],
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 22.82,
                                top: 162.25,
                                child: Container(
                                  width: 28.71,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.4000000059604645),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 97.47,
                                top: 162.25,
                                child: Container(
                                  width: 28.71,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 98,
                                top: 164,
                                child: Container(
                                  width: 27,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 6.08,
                                        top: 7.43,
                                        child: Container(
                                          width: 18.26,
                                          height: 14.85,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0.67,
                                                top: 0,
                                                child: Opacity(
                                                  opacity: 0.20,
                                                  child: Container(
                                                    width: 17.58,
                                                    height: 14.85,
                                                    child: Stack(children: [
                                                    ,
                                                    ]),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24,
                                top: 164,
                                child: Container(
                                  width: 26,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(children: [
                                  ,
                                  ]),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 5,
                                child: Container(
                                  width: 72.70,
                                  height: 43.62,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 10.92,
                                        top: 3.25,
                                        child: Container(
                                          width: 60.58,
                                          height: 13.75,
                                          decoration: ShapeDecoration(
                                            color: Colors.white.withOpacity(0.25),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12.43,
                                        top: 4.62,
                                        child: Container(
                                          width: 12.12,
                                          height: 11,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                      Positioned(
                                        left: 22,
                                        top: 0,
                                        child: SizedBox(
                                          width: 45,
                                          height: 27,
                                          child: Text(
                                            'East Java',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 7,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.41,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 14,
                                        child: SizedBox(
                                          width: 72.70,
                                          height: 20.62,
                                          child: Text(
                                            'Bromo Mt',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 10,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.20,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 9.89,
                                        top: 28.50,
                                        child: Container(
                                          width: 56.04,
                                          height: 15.12,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 16.66,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 16.66,
                                                          height: 15.12,
                                                          clipBehavior: Clip.antiAlias,
                                                          decoration: BoxDecoration(),
                                                          child: Stack(children: [
                                                          ,
                                                          ]),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 9.09,
                                                top: 0,
                                                child: Container(
                                                  width: 18.17,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 19.69,
                                                top: 0,
                                                child: Container(
                                                  width: 16.66,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 28.78,
                                                top: 0,
                                                child: Container(
                                                  width: 18.17,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 39.38,
                                                top: 0,
                                                child: Container(
                                                  width: 16.66,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 162.38,
                        top: -0,
                        child: Container(
                          width: 150.62,
                          height: 209,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 4.76,
                                top: 0,
                                child: Container(
                                  width: 145.86,
                                  height: 209,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/146x209"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 3.62,
                                top: 178.75,
                                child: Container(
                                  width: 147,
                                  height: 30.25,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, -1.00),
                                      end: Alignment(0, 1),
                                      colors: [Color(0x00D9D9D9), Color(0xFF1E1E1E)],
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 25.28,
                                top: 162.25,
                                child: Container(
                                  width: 28.49,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 99.35,
                                top: 162.25,
                                child: Container(
                                  width: 28.49,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 99.62,
                                top: 163.62,
                                child: Container(
                                  width: 27,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 6.07,
                                        top: 7.43,
                                        child: Container(
                                          width: 18.26,
                                          height: 14.85,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0.68,
                                                top: 0,
                                                child: Opacity(
                                                  opacity: 0.20,
                                                  child: Container(
                                                    width: 17.58,
                                                    height: 14.85,
                                                    child: Stack(children: [
                                                    ,
                                                    ]),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 26.69,
                                top: 163.62,
                                child: Container(
                                  width: 26,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(children: [
                                  ,
                                  ]),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 5,
                                child: Container(
                                  width: 89.20,
                                  height: 42.62,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 13.54,
                                        top: 3.25,
                                        child: Container(
                                          width: 61.52,
                                          height: 13.75,
                                          decoration: ShapeDecoration(
                                            color: Colors.white.withOpacity(0.25),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 15.08,
                                        top: 4.62,
                                        child: Container(
                                          width: 12.30,
                                          height: 11,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                      Positioned(
                                        left: 20.62,
                                        top: 0,
                                        child: SizedBox(
                                          width: 58,
                                          height: 28,
                                          child: Text(
                                            'Central Java',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 7,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.41,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 14.25,
                                        child: SizedBox(
                                          width: 89.20,
                                          height: 20.62,
                                          child: Text(
                                            'Merbabu Mt',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 10,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.20,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12.46,
                                        top: 27.50,
                                        child: Container(
                                          width: 56.90,
                                          height: 15.12,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 16.92,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 16.92,
                                                          height: 15.12,
                                                          clipBehavior: Clip.antiAlias,
                                                          decoration: BoxDecoration(),
                                                          child: Stack(children: [
                                                          ,
                                                          ]),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 9.23,
                                                top: -0,
                                                child: Container(
                                                  width: 18.46,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 19.99,
                                                top: -0,
                                                child: Container(
                                                  width: 16.92,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 29.22,
                                                top: -0,
                                                child: Container(
                                                  width: 18.46,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 39.99,
                                                top: -0,
                                                child: Container(
                                                  width: 16.92,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 326,
                        top: 0,
                        child: Container(
                          width: 147,
                          height: 209,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 1.16,
                                top: -0,
                                child: Container(
                                  width: 145.84,
                                  height: 209,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/146x209"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 179,
                                child: Container(
                                  width: 147,
                                  height: 30,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, -1.00),
                                      end: Alignment(0, 1),
                                      colors: [Color(0x00D9D9D9), Color(0xFF1E1E1E)],
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 21.99,
                                top: 162.25,
                                child: Container(
                                  width: 28.94,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 97.23,
                                top: 162.25,
                                child: Container(
                                  width: 28.94,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 98.70,
                                top: 163.62,
                                child: Container(
                                  width: 27,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 6.07,
                                        top: 7.43,
                                        child: Container(
                                          width: 18.26,
                                          height: 14.85,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0.68,
                                                top: 0,
                                                child: Opacity(
                                                  opacity: 0.20,
                                                  child: Container(
                                                    width: 17.58,
                                                    height: 14.85,
                                                    child: Stack(children: [
                                                    ,
                                                    ]),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 23.46,
                                top: 163.62,
                                child: Container(
                                  width: 26,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(children: [
                                  ,
                                  ]),
                                ),
                              ),
                              Positioned(
                                left: 3.35,
                                top: 5.38,
                                child: Container(
                                  width: 67.68,
                                  height: 43.25,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 6.41,
                                        top: 2.88,
                                        child: Container(
                                          width: 56.40,
                                          height: 13.75,
                                          decoration: ShapeDecoration(
                                            color: Colors.white.withOpacity(0.25),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 7.82,
                                        top: 4.25,
                                        child: Container(
                                          width: 11.28,
                                          height: 11,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                      Positioned(
                                        left: 23.15,
                                        top: 0,
                                        child: SizedBox(
                                          width: 26.79,
                                          height: 27.50,
                                          child: Text(
                                            'Lombok',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 7,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.41,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 13.88,
                                        child: SizedBox(
                                          width: 67.68,
                                          height: 20.62,
                                          child: Text(
                                            'Rinjani Mt',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 10,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.20,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 7.59,
                                        top: 28.12,
                                        child: Container(
                                          width: 52.17,
                                          height: 15.12,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 15.51,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 15.51,
                                                          height: 15.12,
                                                          clipBehavior: Clip.antiAlias,
                                                          decoration: BoxDecoration(),
                                                          child: Stack(children: [
                                                          ,
                                                          ]),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 8.46,
                                                top: -0,
                                                child: Container(
                                                  width: 16.92,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 18.33,
                                                top: -0,
                                                child: Container(
                                                  width: 15.51,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 26.79,
                                                top: -0,
                                                child: Container(
                                                  width: 16.92,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 36.66,
                                                top: -0,
                                                child: Container(
                                                  width: 15.51,
                                                  height: 15.12,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 485,
                        top: -1,
                        child: Container(
                          width: 147,
                          height: 209,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 146,
                                  height: 209,
                                  decoration: ShapeDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/146x209"),
                                      fit: BoxFit.fill,
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                    shadows: [
                                      BoxShadow(
                                        color: Color(0x3F000000),
                                        blurRadius: 4,
                                        offset: Offset(0, 4),
                                        spreadRadius: 0,
                                      )
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 180.39,
                                child: Container(
                                  width: 147,
                                  height: 28.61,
                                  decoration: ShapeDecoration(
                                    gradient: LinearGradient(
                                      begin: Alignment(0.00, -1.00),
                                      end: Alignment(0, 1),
                                      colors: [Color(0x00D9D9D9), Color(0xFF1E1E1E)],
                                    ),
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10.05,
                                top: 8,
                                child: Container(
                                  width: 50.26,
                                  height: 41.06,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 3.15,
                                        child: Container(
                                          width: 50.26,
                                          height: 13,
                                          decoration: ShapeDecoration(
                                            color: Colors.white.withOpacity(0.25),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 1.26,
                                        top: 4.45,
                                        child: Container(
                                          width: 10.05,
                                          height: 10.40,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                      Positioned(
                                        left: 13.95,
                                        top: 0,
                                        child: SizedBox(
                                          width: 26,
                                          height: 26,
                                          child: Text(
                                            'Dieng',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 7,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.41,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0.26,
                                        top: 13.55,
                                        child: SizedBox(
                                          width: 45.23,
                                          height: 19.51,
                                          child: Text(
                                            'Prau Mt',
                                            textAlign: TextAlign.center,
                                            style: TextStyle(
                                              color: Colors.white,
                                              fontSize: 10,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w300,
                                              height: 0.20,
                                              letterSpacing: -0.24,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 1.49,
                                        top: 26.76,
                                        child: Container(
                                          width: 46.49,
                                          height: 14.30,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 0,
                                                child: Container(
                                                  width: 13.82,
                                                  height: 14.30,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Container(
                                                          width: 13.82,
                                                          height: 14.30,
                                                          clipBehavior: Clip.antiAlias,
                                                          decoration: BoxDecoration(),
                                                          child: Stack(children: [
                                                          ,
                                                          ]),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 7.54,
                                                top: 0,
                                                child: Container(
                                                  width: 15.08,
                                                  height: 14.30,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 16.33,
                                                top: 0,
                                                child: Container(
                                                  width: 13.82,
                                                  height: 14.30,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 23.87,
                                                top: 0,
                                                child: Container(
                                                  width: 15.08,
                                                  height: 14.30,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                              Positioned(
                                                left: 32.67,
                                                top: 0,
                                                child: Container(
                                                  width: 13.82,
                                                  height: 14.30,
                                                  clipBehavior: Clip.antiAlias,
                                                  decoration: BoxDecoration(),
                                                  child: Stack(children: [
                                                  ,
                                                  ]),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 19.99,
                                top: 162.25,
                                child: Container(
                                  width: 28.94,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 95.23,
                                top: 162.25,
                                child: Container(
                                  width: 28.94,
                                  height: 31.62,
                                  decoration: ShapeDecoration(
                                    color: Colors.white.withOpacity(0.5),
                                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(5)),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 96.70,
                                top: 163.62,
                                child: Container(
                                  width: 27,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 6.07,
                                        top: 7.43,
                                        child: Container(
                                          width: 18.26,
                                          height: 14.85,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0.68,
                                                top: 0,
                                                child: Opacity(
                                                  opacity: 0.20,
                                                  child: Container(
                                                    width: 17.58,
                                                    height: 14.85,
                                                    child: Stack(children: [
                                                    ,
                                                    ]),
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 21.46,
                                top: 163.62,
                                child: Container(
                                  width: 26,
                                  height: 27,
                                  clipBehavior: Clip.antiAlias,
                                  decoration: BoxDecoration(),
                                  child: Stack(children: [
                                  ,
                                  ]),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 404,
                child: Container(
                  width: 397,
                  height: 401.78,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 29,
                        child: Container(
                          width: 304,
                          height: 372.78,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 304,
                                  height: 190.78,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 12,
                                        top: 12.79,
                                        child: Container(
                                          width: 280,
                                          height: 118.30,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/280x118"),
                                              fit: BoxFit.cover,
                                            ),
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12,
                                        top: 137.49,
                                        child: SizedBox(
                                          width: 119,
                                          height: 40.50,
                                          child: Text.rich(
                                            TextSpan(
                                              children: [
                                                TextSpan(
                                                  text: 'The Most Beatifull View\n',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 10,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0,
                                                  ),
                                                ),
                                                TextSpan(
                                                  text: 'Ijen Mount ',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 14,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w700,
                                                    height: 0,
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 224,
                                        top: 157.74,
                                        child: SizedBox(
                                          width: 68,
                                          height: 19.18,
                                          child: Text(
                                            'View Detail',
                                            style: TextStyle(
                                              color: Color(0xFF674CEE),
                                              fontSize: 12,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w600,
                                              textDecoration: TextDecoration.underline,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 182,
                                child: Container(
                                  width: 304,
                                  height: 190.78,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 12,
                                        top: 12.79,
                                        child: Container(
                                          width: 280,
                                          height: 118.30,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://via.placeholder.com/280x118"),
                                              fit: BoxFit.cover,
                                            ),
                                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 12,
                                        top: 137.49,
                                        child: SizedBox(
                                          width: 194,
                                          height: 40.50,
                                          child: Text.rich(
                                            TextSpan(
                                              children: [
                                                TextSpan(
                                                  text: 'For You Cold Mount\n',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 10,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0,
                                                  ),
                                                ),
                                                TextSpan(
                                                  text: 'Arjuna Mount',
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 14,
                                                    fontFamily: 'Poppins',
                                                    fontWeight: FontWeight.w700,
                                                    height: 0,
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 224,
                                        top: 157.74,
                                        child: SizedBox(
                                          width: 68,
                                          height: 19.18,
                                          child: Text(
                                            'View Detail',
                                            style: TextStyle(
                                              color: Color(0xFF674CEE),
                                              fontSize: 12,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w600,
                                              textDecoration: TextDecoration.underline,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 397,
                          height: 35.17,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(
                                  width: 118,
                                  height: 35.17,
                                  child: Text(
                                    'Best offers',
                                    style: TextStyle(
                                      color: Colors.black,
                                      fontSize: 22,
                                      fontFamily: 'Poppins',
                                      fontWeight: FontWeight.w600,
                                      height: 0,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 327,
                                top: 4.26,
                                child: Container(
                                  width: 70,
                                  height: 25.58,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 3.20,
                                        child: SizedBox(
                                          width: 40,
                                          height: 19.18,
                                          child: Text(
                                            'See all',
                                            style: TextStyle(
                                              color: Color(0xFF674CEE),
                                              fontSize: 12,
                                              fontFamily: 'Poppins',
                                              fontWeight: FontWeight.w600,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 46,
                                        top: 0,
                                        child: Container(
                                          width: 24,
                                          height: 25.58,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: Stack(children: [
                                          ,
                                          ]),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 106,
                top: 61,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Hi Demi?\n',
                        style: TextStyle(
                          color: Color(0xFF2B2D33),
                          fontSize: 24,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 0.08,
                        ),
                      ),
                      TextSpan(
                        text: 'What’s Are You Destination',
                        style: TextStyle(
                          color: Color(0xFF2B2D33),
                          fontSize: 16,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w500,
                          height: 0.17,
                        ),
                      ),
                    ],
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
              Positioned(
                left: 0,
                top: 850,
                child: Container(
                  width: 414,
                  height: 46,
                  padding: const EdgeInsets.only(top: 13.28, left: 52, bottom: 13.28),
                  decoration: ShapeDecoration(
                    color: Color(0xFF00D18A),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(16.60),
                        topRight: Radius.circular(16.60),
                      ),
                    ),
                    shadows: [
                      BoxShadow(
                        color: Color(0x99000000),
                        blurRadius: 16.60,
                        offset: Offset(0, -2.21),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Container(
                        width: 35,
                        height: 29,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(children: [
                        ,
                        ]),
                      ),
                      const SizedBox(width: 58),
                      Container(
                        width: 31,
                        height: 29,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(children: [
                        ,
                        ]),
                      ),
                      const SizedBox(width: 58),
                      Container(
                        width: 28,
                        height: 22,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(children: [
                        ,
                        ]),
                      ),
                      const SizedBox(width: 58),
                      Container(
                        width: 25,
                        height: 22,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(children: [
                        ,
                        ]),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 16,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        '9:41',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFF4F4F4F),
                          fontSize: 15,
                          fontFamily: 'SF Pro Text',
                          fontWeight: FontWeight.w600,
                          height: 0.09,
                          letterSpacing: -0.24,
                        ),
                      ),
                      const SizedBox(width: 277),
                      Container(
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Container(
                              width: 17,
                              height: 10.67,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/17x11"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 8),
                            Container(
                              width: 15.33,
                              height: 11,
                              decoration: BoxDecoration(
                                image: DecorationImage(
                                  image: NetworkImage("https://via.placeholder.com/15x11"),
                                  fit: BoxFit.fill,
                                ),
                              ),
                            ),
                            const SizedBox(width: 8),
                            Container(
                              width: 24.66,
                              height: 11,
                              child: Stack(
                                children: [
                                  Positioned(
                                    left: 0,
                                    top: 0,
                                    child: Opacity(
                                      opacity: 0.35,
                                      child: Container(
                                        width: 22,
                                        height: 11,
                                        decoration: ShapeDecoration(
                                          shape: RoundedRectangleBorder(
                                            side: BorderSide(width: 1, color: Color(0xFF4F4F4F)),
                                            borderRadius: BorderRadius.circular(2.67),
                                          ),
                                        ),
                                      ),
                                    ),
                                  ),
                                  Positioned(
                                    left: 2,
                                    top: 2,
                                    child: Container(
                                      width: 18,
                                      height: 7,
                                      decoration: ShapeDecoration(
                                        color: Color(0xFF4F4F4F),
                                        shape: RoundedRectangleBorder(
                                          borderRadius: BorderRadius.circular(1.33),
                                        ),
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 322,
                top: 59,
                child: Container(
                  width: 67,
                  height: 66.13,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 67,
                          height: 66.13,
                          decoration: ShapeDecoration(
                            color: Color(0xFF2F80ED),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 67,
                          height: 66.13,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 67,
                                  height: 66.13,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFF9A826),
                                    shape: OvalBorder(),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 2.33,
                                top: 3.18,
                                child: Container(
                                  width: 67,
                                  height: 68.23,
                                  decoration: BoxDecoration(
                                    image: DecorationImage(
                                      image: NetworkImage("https://via.placeholder.com/67x68"),
                                      fit: BoxFit.fill,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}